version: '3'

services:
  php:
    build: .
    container_name: ProjetoF1
    ports:
      - 8080:80
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    tty: true
    volumes:
      - .:/var/www/html
