name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Run Composer Install
      run: composer run-script composer

    - name: Update Autoload
      run: composer run-script autoload

    - name: Run tests suite
      run: composer run-script tests